#!/bin/bash

DIR=$(dirname $(realpath $0))

set -x
ln -sf $DIR/bashrc     ~/.bashrc
ln -sf $DIR/gtkrc-2.0  ~/.gtkrc-2.0
ln -sf $DIR/screenrc   ~/.screenrc
ln -sf $DIR/taskrc     ~/.taskrc
ln -sf $DIR/vimrc      ~/.vimrc
ln -sf $DIR/XCompose   ~/.XCompose
ln -sf $DIR/Xresources ~/.Xresources

