#!/bin/bash

DIR=$(dirname $(realpath $0))

dotinstall() {
	if [ -e ~/$2 ]; then
		NEWFILE=$2.$(date +%F_%T)
		echo "Renaming $2 to $NEWFILE..."
		mv ~/$2 ~/$NEWFILE
	fi

	mkdir -p $(dirname ~/$2)

	echo "Linking $1 to $2...."
	ln -sf $DIR/$1 ~/$2
}

setup_vim() {
	cd $DIR && git submodule init && git submodule update
}

case $1 in
	deps|dependencies)
		if [ -f /usr/bin/apt-get ]; then
			sudo /usr/bin/apt-get install coreutils realpath
		elif [ -f /usr/bin/yum ]; then
			sudo /usr/bin/yum install coreutils
		fi
		;;

	clean)
		rm -f ~/.bash_profile.*
		rm -f ~/.bashrc.*
		rm -f ~/.gtkrc-2.0.*
		rm -f ~/.screenrc.*
		rm -f ~/.vim.*
		rm -f ~/.vimrc.*
		rm -f ~/bin/__bash_prompt.*
		rm -f ~/.taskrc.*
		rm -f ~/.XCompose.*
		rm -f ~/.Xresources.*
		rm -f ~/.gitconfig.*
		;;

	*)
		dotinstall bash_profile      .bash_profile
		dotinstall bashrc            .bashrc
		dotinstall gtkrc-2.0         .gtkrc-2.0
		dotinstall screenrc          .screenrc
		dotinstall vimrc             .vimrc
		dotinstall vim               .vim
		dotinstall taskrc            .taskrc
		dotinstall XCompose          .XCompose
		dotinstall Xresources        .Xresources
		dotinstall initrc            .initrc
		dotinstall bin/__bash_prompt bin/__bash_prompt
		dotinstall gitconfig         .gitconfig
		setup_vim
		;;
esac

