INSTALL=sudo install -vc -o root

install:
	@sudo mkdir -p /usr/share/lxdm/themes/LinuxLogo
	$(INSTALL) etc/lxdm/lxdm.conf /etc/lxdm/
	$(INSTALL) usr/share/backgrounds/gradient.png /usr/share/backgrounds/
	$(INSTALL) usr/share/lxdm/themes/LinuxLogo/* /usr/share/lxdm/themes/LinuxLogo
