INSTALL=sudo install -vc -o root

install:
	@sudo mkdir -p /usr/share/lxdm/themes/LinuxLogo
	$(INSTALL) lxdm.conf /etc/lxdm/
	$(INSTALL) gradient.png /usr/share/backgrounds/
	$(INSTALL) LinuxLogo/* /usr/share/lxdm/themes/LinuxLogo
