alias abook='abook --config /home/pfsmorigo/.config/abook/abookrc --datafile /home/pfsmorigo/.config/abook/addressbook'
alias b='buku --np --oa -S'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias ga='git add'
alias gb='git branch'
alias gc='git commit'
alias gd='git diff'
alias gl='git log'
alias gll='git log2'
alias google-chrome='google-chrome --force-device-scale-factor=1.2 --force-dark-mode'
alias grep='grep --color=auto'
alias gs='git status'
alias gss='git status --short'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -lF'
alias ls='ls --color=auto'
alias m='time make -j8'
alias qd='quilt diff'
alias qr='quilt refresh'
alias qs='quilt series'
alias s='screen_switch'
