#set -g theme_color_scheme user
set -g theme_date_timezone America/Sao_Paulo
set -g theme_display_cmd_duration yes
set -g theme_display_git yes
set -g theme_display_git_ahead_verbose yes
set -g theme_display_git_dirty_verbose yes
set -g theme_display_hostname yes
set -g theme_display_jobs_verbose yes
set -g theme_show_exit_status yes
set -g theme_title_use_abbreviated_path yes
