[[keys]]
  index = 0
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = "assets/back.png"
  [keys.action]
    deck = "~/.config/deckmaster/main.toml"

[[keys]]
  index = 10
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = "assets/brightness_low.png"
  [keys.action]
    device = "sleep"
    deck = "~/.config/deckmaster/main.toml"

[[keys]]
  index = 11
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = "assets/brightness_25.png"
  [keys.action]
    device = "brightness=15"

[[keys]]
  index = 12
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = "assets/brightness_50.png"
  [keys.action]
    device = "brightness=30"

[[keys]]
  index = 13
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = "assets/brightness_75.png"
  [keys.action]
    device = "brightness=40"

[[keys]]
  index = 14
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = "assets/brightness_high.png"
  [keys.action]
    device = "brightness=100"
