[[keys]]
  index = 0
  [keys.widget]
    id = "top"
    [keys.widget.config]
      mode = "cpu"
      fillColor = "#00f"
      borderColor = "#0f0"
      history = 3
      history2 = 3

[[keys]]
  index = 1
  [keys.widget]
    id = "top"
    [keys.widget.config]
      mode = "memory"
      fillColor = "#090"

[[keys]]
  index = 2
  [keys.widget]
    id = "weather"

[[keys]]
  index = 3
  [keys.widget]
    id = "time"
    [keys.widget.config]
      format = "%l;%d;%M"
      font = "regular;bold;regular"

[[keys]]
  index = 4
  [keys.widget]
    id = "time"
    [keys.widget.config]
      format = "%H;%i;%s"
      font = "bold;regular;thin"
  [keys.action]
    deck = "~/.config/deckmaster/blank.deck"

[[keys]]
  index = 5
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = "assets/volume-low.png"
      label = "Lower Vol"
      fontsize = 8
  [keys.action]
    keycode = "VolumeDown"
  [keys.action_hold]
    keycode = "Mute"

[[keys]]
  index = 6
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = "assets/volume-high.png"
      label = "Raise Vol"
      fontsize = 8
  [keys.action]
    keycode = "VolumeUp"
  [keys.action_hold]
    keycode = "Mute"

[[keys]]
  index = 7
  [keys.widget]
    id = "button"
    [keys.widget.config]
      label = "Sleep"
  [keys.action]
    device = "sleep"

[[keys]]
  index = 8
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = "assets/go-previous.png"
      label = "Dim"
  [keys.action]
    device = "brightness-10"

[[keys]]
  index = 9
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = "assets/go-next.png"
      label = "Brighten"
  [keys.action]
    device = "brightness+10"

[[keys]]
  index = 10
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = "assets/play_pause.png"
  [keys.action]
    keycode = "Playpause"
  [keys.action_hold]
    keycode = "Mute"

[[keys]]
  index = 11
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = "assets/fast_forward.png"
  [keys.action]
    keycode = "Nextsong"
  [keys.action_hold]
    keycode = "Previoussong"

[[keys]]
  index = 12
  [keys.widget]
    id = "command"
    [keys.widget.config]
      command = "echo 'ESM Standup'; echo '14:00'"
      font = "regular;bold" # optional
      color = "#fefefe" # optional
	  layout = "0x0+72x20;0x12+72x52" # optional

[[keys]]
  index = 13
  [keys.widget]
    id = "command"
    [keys.widget.config]
      command = "echo 'Pomodoro'; ~/scripts/all/pomodoro"
      font = "regular;bold" # optional
      color = "#fefefe" # optional
	  layout = "0x0+72x20;0x12+72x52" # optional
  [keys.action]
      exec = "~/scripts/all/pomodoro start"
  [keys.action_hold]
      exec = "~/scripts/all/pomodoro reset"

[[keys]]
  index = 14
  [keys.widget]
    id = "command"
    [keys.widget.config]
      command = "echo 'Downloads'; ls -a ~/downloads | wc -l"
      font = "regular;bold" # optional
      color = "#fefefe" # optional
	  layout = "0x0+72x20;0x12+72x52" # optional

