[[keys]]
  index = 0
  [keys.widget]
    id = "top"
    [keys.widget.config]
      mode = "cpu"
      fillColor = "#00f"
	  borderColor = "#000"
      history = 100

[[keys]]
  index = 1
  [keys.widget]
    id = "top"
    [keys.widget.config]
      mode = "memory"
      fillColor = "#090"
      borderColor = "#000"
      history = 100

[[keys]]
  index = 2
  [keys.widget]
    id = "weather"

[[keys]]
  index = 3
  [keys.widget]
    id = "time"
    [keys.widget.config]
      format = "%l;%d;%M"
      font = "regular;bold;regular"

[[keys]]
  index = 4
  [keys.widget]
    id = "time"
    [keys.widget.config]
      format = "%H;%i;%s"
      font = "bold;regular;thin"
  [keys.action]
    deck = "~/.config/deckmaster/config.toml"

[[keys]]
  index = 5
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = "assets/volume_down.png"
  [keys.action]
    keycode = "VolumeDown"
  [keys.action_hold]
    keycode = "Mute"

[[keys]]
  index = 6
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = "assets/volume_up.png"
  [keys.action]
    keycode = "VolumeUp"
  [keys.action_hold]
    keycode = "Mute"

[[keys]]
  index = 10
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = "assets/play_pause.png"
  [keys.action]
    keycode = "Playpause"
  [keys.action_hold]
    keycode = "Mute"

[[keys]]
  index = 11
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = "assets/fast_forward.png"
  [keys.action]
    keycode = "Nextsong"
  [keys.action_hold]
    keycode = "Previoussong"

[[keys]]
  index = 12
  [keys.widget]
    id = "command"
    [keys.widget.config]
      command = "echo 'ESM Standup'; echo '14:00'"
      font = "regular;bold" # optional
      color = "#fefefe" # optional
	  layout = "0x0+72x20;0x12+72x52" # optional

[[keys]]
  index = 13
  [keys.widget]
    id = "command"
    [keys.widget.config]
      command = "echo 'Pomodoro'; ~/scripts/all/pomodoro"
      font = "regular;bold" # optional
      color = "#fefefe" # optional
	  layout = "0x0+72x20;0x12+72x52" # optional
  [keys.action]
      exec = "~/scripts/all/pomodoro start"
  [keys.action_hold]
      exec = "~/scripts/all/pomodoro reset"

[[keys]]
  index = 14
  [keys.widget]
    id = "command"
    [keys.widget.config]
      command = "echo 'Downloads'; ls -a ~/downloads | wc -l"
      font = "regular;bold" # optional
      color = "#fefefe" # optional
	  layout = "0x0+72x20;0x12+72x52" # optional

