[[keys]]
  index = 0
  interval = 5000
  [keys.widget]
    id = "command"
    [keys.widget.config]
      command = "echo oslo;~/scripts/all/deckmaster_helper ping oslo.lan"
      font = "regular;bold"
      color = "#fefefe"
	  layout = "0x0+72x12;0x20+72x30"

[[keys]]
  index = 5
  interval = 5000
  [keys.widget]
    id = "homeassistant"
    [keys.widget.config]
      entity_name = true
      alias = "Main"
      icon_on = "assets/home_assistant_light_on.png"
      icon_off = "assets/home_assistant_light_off.png"
      entity_id = "light.downstairs_office_lights_main"
      url = "https://home.smow.io"
      token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI3NjI2YzU2Njc2ZjY0OTMxYmViNGY4MGMxYmI4MjVkMyIsImlhdCI6MTc0MDIyNTY0NCwiZXhwIjoyMDU1NTg1NjQ0fQ.XsASk1ov4ADge1slThiD2ex9MC3z0HzFavT8gWLfGQA"
      service = "light.toggle"

[[keys]]
  index = 6
  interval = 5000
  [keys.widget]
    id = "homeassistant"
    [keys.widget.config]
      entity_name = true
      alias = "Secondary"
      icon_on = "assets/home_assistant_light_on.png"
      icon_off = "assets/home_assistant_light_off.png"
      entity_id = "light.downstairs_office_lights_secondary"
      url = "https://home.smow.io"
      token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI3NjI2YzU2Njc2ZjY0OTMxYmViNGY4MGMxYmI4MjVkMyIsImlhdCI6MTc0MDIyNTY0NCwiZXhwIjoyMDU1NTg1NjQ0fQ.XsASk1ov4ADge1slThiD2ex9MC3z0HzFavT8gWLfGQA"
      service = "light.toggle"

[[keys]]
  index = 7
  interval = 5000
  [keys.widget]
    id = "homeassistant"
    [keys.widget.config]
      entity_name = true
      alias = "Wall"
      icon_on = "assets/home_assistant_light_on.png"
      icon_off = "assets/home_assistant_light_off.png"
      entity_id = "light.downstairs_office_lights_wall"
      url = "https://home.smow.io"
      token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI3NjI2YzU2Njc2ZjY0OTMxYmViNGY4MGMxYmI4MjVkMyIsImlhdCI6MTc0MDIyNTY0NCwiZXhwIjoyMDU1NTg1NjQ0fQ.XsASk1ov4ADge1slThiD2ex9MC3z0HzFavT8gWLfGQA"
      service = "light.toggle"

[[keys]]
  index = 8
  interval = 5000
  [keys.widget]
    id = "homeassistant"
    [keys.widget.config]
      entity_name = true
      alias = "Desk"
      icon_on = "assets/home_assistant_light_on.png"
      icon_off = "assets/home_assistant_light_off.png"
      entity_id = "light.downstairs_office_desk_light"
      url = "https://home.smow.io"
      token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI3NjI2YzU2Njc2ZjY0OTMxYmViNGY4MGMxYmI4MjVkMyIsImlhdCI6MTc0MDIyNTY0NCwiZXhwIjoyMDU1NTg1NjQ0fQ.XsASk1ov4ADge1slThiD2ex9MC3z0HzFavT8gWLfGQA"
      service = "light.toggle"

[[keys]]
  index = 10
  interval = 5000
  [keys.widget]
    id = "homeassistant"
    [keys.widget.config]
      entity_name = true
      alias = "Climate"
      icon_on = "assets/home_assistant_climate_on.png"
      icon_off = "assets/home_assistant_climate_off.png"
      entity_id = "climate.downstairs_office"
      url = "https://home.smow.io"
      token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI3NjI2YzU2Njc2ZjY0OTMxYmViNGY4MGMxYmI4MjVkMyIsImlhdCI6MTc0MDIyNTY0NCwiZXhwIjoyMDU1NTg1NjQ0fQ.XsASk1ov4ADge1slThiD2ex9MC3z0HzFavT8gWLfGQA"
      service = "light.toggle"

[[keys]]
  index = 14
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = "assets/back.png"
  [keys.action]
    deck = "~/.config/deckmaster/main.toml"

