deck:
  - card: custom
    unicode: 🔆
    background-color: "#000"
    title: Off
    press:
      device: sleep

  - card: custom
    unicode: 🔆
    background-color: "#222"
    title: 25%
    press:
      device: brightness=25

  - card: custom
    unicode: 🔆
    background-color: "#444"
    title: 50%
    press:
      device: brightness=50

  - card: custom
    unicode: 🔆
    background-color: "#666"
    title: 75%
    press:
      device: brightness=75

  - card: custom
    unicode: 🔆
    background-color: "#888"
    title: 100%
    press:
      device: brightness=100
