#!/bin/bash

complement() {
	if [ "$(iwgetid | cut -d' ' -f1)" = "$1" ]; then
		echo " ($(iwgetid -r))"
	else
		SPEED="$(cat /sys/class/net/$1/speed 2> /dev/null)"
		[ -n "$SPEED" ] && echo " ($SPEED Mbps)"
	fi
}

OUTPUT=

OLDIFS=$IFS
IFS=$'\n'
for IF in $(ip -o -4 a); do
	NAME=$(echo $IF | awk '{ print $2 }')
	IP=$(echo $IF | awk '{ print $4 }' | cut -d/ -f1)

	case $NAME in
		lo|virbr*)   continue ;;
		em*)         ICON= ;; # ethernet
		enp0s26u1u2) ICON= ;; # usb
		tun*)        ICON= ;; # vpn
		wlp3s0)      ICON= ;; # wireless
		*)           ICON= ;; # generic
	esac
	OUTPUT+="$ICON $IP$(complement $NAME)   "
done
IFS=$OLDIFS

if [ -z "$(echo $OUTPUT | xargs)" ]; then
   echo "no network"
   echo ""
   echo "#ff0000"
else
   echo "$OUTPUT" | sed 's/^ *//; s/ *$//'
fi
