# vim:fileencoding=utf-8:foldmethod=marker

# --- Fonts ---
font_family      Ubuntu
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

# --- Color Scheme ---
#include current-theme.conf

# --- Cursor ---
cursor_shape     block
cursor_blink_interval 0.3

# --- Window Layout & Padding ---
window_padding_width 4
hide_window_decorations no
remember_window_size yes

# --- Tab Bar ---
tab_bar_style    powerline
tab_powerline_style slanted

background_opacity 0.75
dynamic_background_opacity yes
inactive_text_alpha 0.5

url_style straight


# --- Keybindings ---
map ctrl+alt+c copy_to_clipboard
map ctrl+alt+v paste_from_clipboard
map ctrl+equal change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0     change_font_size all 0


# --- Others ---
confirm_os_window_close 0

# Disable translating mouse wheel into Up/Down arrows in alternate screen mode
touch_scroll_multiplier 1.0
wheel_scroll_multiplier 5.0

# Ensure kitty does not map scrolling to cursor keys
map shift+up scroll_line_up
map shift+down scroll_line_down
map shift+page_up scroll_page_up
map shift+page_down scroll_page_down
